### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Sailoriae**
Hello !
I couldn't find your Crowding, so here's a PR with my complete french translation of your plugin.
The problem is that I don't understand how you made your language loading system, but it doesn't load. So I coundn't test it in game.
Have a nice day !

### CODE REVIEW

**Review by Narimm — APPROVED** [review]

**Comment by Sailoriae** [comment]
@Narimm Hello ! ^^ Why did you merge your `master` branch into mine ? 🤔

**Comment by Sailoriae** [comment]
Heeellllllooo ? ^^

**Comment by Narimm** [comment]
Thats how PR's work - thats a branch update.

**Comment by Sailoriae** [comment]
Thank you for your answer @Narimm ! And for the merge ! ^^

**Pull request merged**
