### PR TITLE
Don't include players Prefix in scoreboard top signs

### PR DESCRIPTION
**Pull request by orkun1675**
The signs have a short line-width, including the full display name doesn't allow the Nick to fit

### CODE REVIEW

**Comment by orkun1675** [comment]
I was thinking about a config option for this but no server has such short prefixes. (maybe *** for pvp servers to show rank?) MC usernames have a limit of 16 characters and signs have 15. So not even all usernames fit.

**Comment by addstar** [comment]
Unfortunately, we rely on using the `displayName` of players because we run a family friendly server and players with offensive names are nicknamed. And we dont want their real usernames to be shown when playing games (and in Minigame broadcasts), so we always use the `displayName`.

If you are willing to add a config option like `useDisplayNames:` (it should default to on, so existing users aren't affected), we'll happily accept another PR :grin: Sorry about that.

**Comment by addstar** [comment]
I should also mention that the `displayName` is used in many places throughout the code, they would all need to be updated to make this change accepted, otherwise it would be inconsistent :wink:

**Comment by orkun1675** [comment]
Will do! Thanks for the quick response.

**Pull request closed without merging**
