### PR TITLE
Include armour slots

### PR DESCRIPTION
**Pull request by MiniWorks18**
Currently, items are only taken from the player's inventory, this should allow items to be taken from their armour slots as well.

## Purpose
_Describe the problem or feature in addition to a link to the issues._

## Approach
_How does this change address the problem?_

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

#### Blog Posts
- [How to Pull Request](https://github.com/flexyford/pull-request) Github Repo with Learning focused Pull Request Template.

### CODE REVIEW

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Regions/src/main/java/au/com/mineauz/minigamesregions/actions/TakeItemAction.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Narimm/Minigames/pullRequest?prid=5381835&bid=17646188)

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Regions/src/main/java/au/com/mineauz/minigamesregions/actions/TakeItemAction.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Narimm/Minigames/pullRequest?prid=5381835&bid=17646188)

**Comment by Narimm** [comment]
Also you cant concat those item arrays like that...it wont meet the slot requirement

**Comment by Narimm** [comment]
Bluntly put this wont work as currently handled.

**Comment by addstar** [comment]
Closing - PR is very old and doesn't seem to have been tested, or provide the functionality in a suitable way.

**Pull request closed without merging**
