### PR TITLE
All dev changes from GreenSurvivors

### PR DESCRIPTION
**Pull request by addstar**
As per the discussion in #381, we decided it would be best for us to just merge in the `dev` branch changes from [GreenSurvivors](https://github.com/GreenSurvivors/GreenMinigames).

Since we no longer do actual releases (or at least, we haven't in a very long time) and Minigames is only available for now as dev builds, we figured it's fine to pull in these dev changes so we can do our own testing/validation. I had planned to just cherry-pick fixes but there were so many good fixes and improvements it wasn't worth it :wink:

If anyone has troubles with these changes, they can revert to the previous build and report the issues to us.

@FireInstall @joshi1999: Just wanted to double check there's nothing in here that you think we should avoid? Also, we've included the changes that add your team to the `plugin.yml` authors, you deserve it! Thank you! :heart:

### CODE REVIEW

**Comment by addstar** [comment]
I noticed a few Codacy issues that I probably agree with, so I might also add a few minor commits to make it happy.

**Comment by FireInstall** [comment]
Looks good to me.
However, please keep in mind you have to merge your changes in the future as all 3 of them got addressed in future changes.

**Comment by addstar** [comment]
> Looks good to me. However, please keep in mind you have to merge your changes in the future as all 3 of them got addressed in future changes.

When you say all 3 do you mean the codacy changes? Or something else? Sorry I'm not sure I understood that.

**Comment by addstar** [comment]
> yeah all 3 codacy changes

Oh no problem, happy to take your fix (I didn't see it) instead, I assume they're very similar to what I did? Or I can just merge this now and just handle the merge conflict later when I pull in your fix.

**Comment by addstar** [comment]
Decided to just merge this and we'll just see how we go in the future and we'll do our testing :slightly_smiling_face: 

Thank you again for all your fixes, improvements and changes! :heart:

**Pull request merged**
