### PR TITLE
Fixed null message on death

### PR DESCRIPTION
**Pull request by Jeanolos**
Fixed a bug, where the death message would display "null" instead of nothing

### CODE REVIEW

**Comment by addstar** [comment]
In your reported issue #40 you mention the word "null" is mentioned in the death message. This does not happen on our servers. Where do you see the "null" death message? Does it say "null" in the normal server death message AND you see the minigames death message as well? Could you provide a screenshot?

**Comment by Jeanolos** [comment]
Sadly, we closed the server few weeks ago. But it said "null" everytime someone died in a Deathmatch. I could only fix it by changing `null` to `""`

**Comment by addstar** [comment]
Sorry you had to close your server, that sucks :frowning: 

Do you remember if the message was only seen by players in the minigame and did it have the "[Minigames]" prefix? or was it a vanilla death message broadcast to everyone with the word "null" in it?

**Comment by addstar** [comment]
Thinking about it again, we don't have this problem and we have never seen this in testing.. but a few others have mentioned it (although the majority don't have this issue). I'd say it's very likely another plugin is causing the problem and only ignoring empty strings, not null strings.

It's possible that while this might work for you, it might not for everyone. We'll do some tests sometime and look whether it's safe/suitable to apply your fix. Thanks.

**Comment by Jeanolos** [comment]
It was a white broadcast vanilla message, just containing the word null. Maybe there was a different plugin interfering with death messages as well, which led into this issue. But I can't check which one it was, since I'm just the developer for the server and therefor, I don't have access to the FTP server.

**Comment by Phumix** [comment]
We are having same problem on our server. Once someone dies in a minigame, a "null" message is being displayed. Using latest version of the plugin.

**Comment by addstar** [comment]
I can't verify this bug because it's not happening on our server, nor have we ever seen it during testing. It really sounds like another plugin is just not handling a "null" death message correctly.

If I remember correctly, a null death message is the correct way to "silence" the vanilla one. I don't want to accept this PR without being sure it won't cause problems for others who don't current have an issue.

I can only suggest doing a test by removing plugins one by one to find the cause. If you can verify this null message still appears with no other plugins, we'll investigate further.

Also, I would recommend using our [WhatIs](http://jenkins.addstar.com.au/job/WhatIs/) plugin to find all plugins listening on the PlayerDeathEvent, since these are the only ones that could be causing the issue.

**Comment by Sharrq** [comment]
This is happening on our 1.9 updated server with the 1.9 Minigames Dev Build. 

I was playing a "snowball fight" arena where snowballs one shot you, and occasionally the snowballs would bounce off something and kill me and it would just say "null" in the chat box. Nothing before it, nothing after it, just the word null.

**Comment by addstar** [comment]
Sorry for the delay in replying, we still haven't seen this problem and we have many Minigames configured on our games server. Unfortunately I can't find this issue.

I'm going to close this ticket, but I would definitely recommend using our [WhatIs](http://jenkins.addstar.com.au/job/WhatIs/) plugin to find all plugins listening on the PlayerDeathEvent, since these are the only ones that could be causing the issue. This may point towards

**Pull request closed without merging**
